#!/bin/sh
set -e


usage() {
    cat >&2 <<EOF
Usage: $0 dataset

Collects the best results from each file in the set of results file.
EOF
}


if [ "$#" -ne 1 ]; then
    usage
    exit 1
fi
dataset="$1"
root_dir="$(dirname $0)"
results_dirs="$(find * -maxdepth 0 -type d | sort)"
for result_dir in $results_dirs; do
    "${root_dir}/get_best" -f "${result_dir}"/out.csv "${dataset}"
done
