#!/bin/bash
# Displays specific columns of a results file.


if [ "$#" -lt 1 ]; then
    echo "Usage: $0 file column,column..." >&2
    exit 1
fi
if [ "$2" ]; then
    exec < "$1"
    shift
fi
cut -d , -f "$1" | column -ts ,
